export const fakeShipments = [
  {
    id: '123456',
    descripcion: 'Cartera',
    tipo: 'Barco',
    origen: 'Los Ángeles',
    destino: 'Miami',
    estado: 'En tránsito',
    peso: '2 kg',
    alto: '25 cm',
    ancho: '15 cm',
    fecha: '2025-06-20',
    oficina: 'Oficina Miami',
  },
  {
    id: '654321',
    descripcion: 'Laptop',
    tipo: 'Avión',
    origen: 'Orlando',
    destino: 'Caracas',
    estado: 'Llegado',
    peso: '3.5 kg',
    alto: '4 cm',
    ancho: '32 cm',
    fecha: '2025-06-12',
    oficina: 'Oficina Caracas',
  },
   {
    id: '123499',
    descripcion: 'disfraz tung tung tung sahur',
    tipo: 'Barco',
    origen: 'Los Ángeles',
    destino: 'Miami',
    estado: 'En tránsito',
    peso: '2 kg',
    alto: '25 cm',
    ancho: '15 cm',
    fecha: '2025-06-20',
    oficina: 'Oficina Miami',
  },
];